#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

VERSION="22.10"
FULL_VERSION="$VERSION.0"
URL="https://github.com/MaharaProject/mahara/archive/refs/tags/21.10.5_RELEASE.tar.gz"

dl $URL /usr/local/src