#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

URL=https://launchpad.net/mahara/1.7/1.7.2/+download/mahara-1.7.2.tar.gz
dl $URL /usr/local/src

