#!/bin/sh -ex

DB_NAME=mahara
DB_USER=mahara
DB_PASS=$(mcookie)

ADMIN_NAME=admin
ADMIN_PASS=turnkey
ADMIN_MAIL=admin@example.com

# convenience symlinks
ln -s /usr/share/mahara /var/www/webroot
ln -s /etc/mahara /var/www/config

# configure apache
a2dissite default
a2ensite mahara
a2enmod rewrite

# start services
/etc/init.d/postgresql start

# create database
PSQLEXEC="psql -U postgres -d postgres -c"
su postgres -c "createuser --no-superuser --createdb --no-createrole $DB_USER"
su postgres -c "createdb --owner $DB_USER $DB_NAME"
$PSQLEXEC "alter user $DB_USER with encrypted password '$DB_PASS';"

# reconfigure mahara
debconf-set-selections << EOF
mahara mahara/db_user string $DB_USER
mahara mahara/db_name string $DB_NAME
mahara mahara/db_pass password $DB_PASS
mahara mahara/db_host string localhost
mahara mahara/smtphosts string localhost
EOF
DEBIAN_FRONTEND=noninteractive dpkg-reconfigure mahara

# stop services
/etc/init.d/postgresql stop

