#!/bin/bash -ex

DB_NAME=mahara
DB_USER=mahara
DB_PASS=$(mcookie)

ADMIN_NAME=admin
ADMIN_PASS=turnkey
ADMIN_MAIL=admin@example.com

SRC=/usr/local/src
WEBROOT=/var/www/mahara
DATADIR=/var/lib/mahara/data

# unpack mahara ans set ownership
tar -zxf $SRC/mahara-*.tar.gz -C $(dirname $WEBROOT)
mv $WEBROOT-*/htdocs $WEBROOT
chown -R www-data:www-data $WEBROOT
rm -rf $WEBROOT-*
rm $SRC/mahara-*.tar.gz

# configure apache
a2dissite 000-default
a2ensite mahara
a2enmod rewrite
a2enmod headers

# start services
/etc/init.d/postgresql start

# create database
su postgres -c "createuser --no-superuser --createdb --no-createrole $DB_USER"
su postgres -c "createdb --owner $DB_USER -EUTF8 $DB_NAME"
su postgres -c "psql postgres" << EOF
alter user $DB_USER with encrypted password '$DB_PASS';
EOF

# create data directory and configuration
mkdir -p $DATADIR
chown -R www-data:www-data $(dirname $DATADIR)

cat > $WEBROOT/config.php <<EOF
<?php
\$cfg = new StdClass;
\$cfg->dbtype = 'postgres';
\$cfg->dbhost = 'localhost';
\$cfg->dbport = null;
\$cfg->dbname = '$DB_NAME';
\$cfg->dbuser = '$DB_USER';
\$cfg->dbpass = '$DB_PASS';
\$cfg->dbprefix = '';
\$cfg->dataroot = '$DATADIR';
\$cfg->emailcontact = '';
\$cfg->passwordsaltmain = '$(mcookie)$(mcookie)';
EOF
chown www-data:www-data $WEBROOT/config.php
chmod 640 $WEBROOT/config.php

# install mahara
cd $WEBROOT
su www-data -s /bin/sh -c "php admin/cli/install.php -p='$ADMIN_PASS' -e=$ADMIN_MAIL"

# setup cron job
echo "
SHELL=/bin/bash

* * * * * php $WEBROOT/lib/cron.php >/dev/null 2>&1
" | crontab -u www-data -

# tweak config
su postgres -c "psql mahara" << EOF
update config set value = 'localhost' where field = 'smtphosts';
update config set value = '25' where field = 'smtpport';
update config set value = 'TurnKey Mahara' where field = 'sitename';
insert into config values('noreplyaddress', 'noreply@example.com');
EOF

# stop services
/etc/init.d/postgresql stop

