#!/bin/bash -e
# regenerate mahara pgsql password

. /etc/default/inithooks

CONF=/etc/mahara/config.debconf.php
PASSWORD=$(mcookie)

sed -i "s|dbpass.*|dbpass   = '$PASSWORD';|" $CONF
$INITHOOKS_PATH/bin/pgsqlconf.py --user=mahara --pass="$PASSWORD"

